# Generated by Django 3.0.6 on 2020-05-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done_status',
            new_name='done',
        ),
    ]
